<?php

$__missing_i18n = [
    'Afinador de Instrumentos' => ['es_ES' => 'Afinador de instrumentos', 'en_US' => 'Instrument tuner'],
    'Agroecologia' => ['es_ES' => 'Agroecología', 'en_US' => 'Agroecology'],
    'Alimentação' => ['es_ES' => 'Alimentación', 'en_US' => 'Food'],
    'Arquitetura-Urbanismo' => ['es_ES' => 'Arquitectura-Urbanismo', 'en_US' => 'Architecture-Urbanism'],
    'Assistente de Produção em geral' => ['es_ES' => 'Asistente de producción en general', 'en_US' => 'General production assistant'],
    'Astronomia e Ufologia' => ['es_ES' => 'Astronomía y Ufología', 'en_US' => 'Astronomy and Ufology'],
    'Audiovisual e Cinema' => ['es_ES' => 'Audiovisual y Cine', 'en_US' => 'Audiovisual and Film'],
    'Cenotécnico(a)' => ['es_ES' => 'Escenotécnico/a', 'en_US' => 'Stage technician'],
    'Ciencia' => ['es_ES' => 'Ciencia', 'en_US' => 'Science'],
    'Ciências Sociais' => ['es_ES' => 'Ciencias Sociales', 'en_US' => 'Social Sciences'],
    'Clima' => ['es_ES' => 'Clima', 'en_US' => 'Climate'],
    'Corpos dissidentes' => ['es_ES' => 'Cuerpos disidentes', 'en_US' => 'Dissident bodies'],
    'Cultura Digital e Tecnologia' => ['es_ES' => 'Cultura Digital y Tecnología', 'en_US' => 'Digital Culture and Technology'],
    'Culturas' => ['es_ES' => 'Culturas', 'en_US' => 'Cultures'],
    'Direitos Humanos' => ['es_ES' => 'Derechos Humanos', 'en_US' => 'Human Rights'],
    'Economias' => ['es_ES' => 'Economías', 'en_US' => 'Economies'],
    'Educação e Formação' => ['es_ES' => 'Educación y Formación', 'en_US' => 'Education and Training'],
    'Engenheiro(a) de Som' => ['es_ES' => 'Ingeniero/a de sonido', 'en_US' => 'Sound engineer'],
    'Ensaiador(a)' => ['es_ES' => 'Ensayador/a', 'en_US' => 'Rehearsal director'],
    'Esporte' => ['es_ES' => 'Deporte', 'en_US' => 'Sport'],
    'Games' => ['es_ES' => 'Juegos', 'en_US' => 'Games'],
    'Geopolitica' => ['es_ES' => 'Geopolítica', 'en_US' => 'Geopolitics'],
    'História e Filosofia' => ['es_ES' => 'Historia y Filosofía', 'en_US' => 'History and Philosophy'],
    'Hospedagem Solidária' => ['es_ES' => 'Hospedaje Solidario', 'en_US' => 'Solidarity lodging'],
    'Iluminador' => ['es_ES' => 'Iluminador', 'en_US' => 'Lighting technician'],
    'Jornalismo' => ['es_ES' => 'Periodismo', 'en_US' => 'Journalism'],
    'Juventude' => ['es_ES' => 'Juventud', 'en_US' => 'Youth'],
    'Leitura e Literatura' => ['es_ES' => 'Lectura y Literatura', 'en_US' => 'Reading and Literature'],
    'Maquiador' => ['es_ES' => 'Maquillador', 'en_US' => 'Makeup artist'],
    'Mediador(a)' => ['es_ES' => 'Mediador/a', 'en_US' => 'Mediator'],
    'Meio Ambiente' => ['es_ES' => 'Medio Ambiente', 'en_US' => 'Environment'],
    'Mestre(a) de Pista' => ['es_ES' => 'Maestro/a de pista', 'en_US' => 'Ringmaster'],
    'Moda' => ['es_ES' => 'Moda', 'en_US' => 'Fashion'],
    'Montador(a)' => ['es_ES' => 'Montador/a', 'en_US' => 'Rigger'],
    'Montador(a) de Palco' => ['es_ES' => 'Montador/a de escenario', 'en_US' => 'Stage rigger'],
    'Movimento PCD' => ['es_ES' => 'Movimiento PCD', 'en_US' => 'Disability rights movement'],
    'Mulher e Feminismos' => ['es_ES' => 'Mujer y Feminismos', 'en_US' => 'Women and Feminisms'],
    'Músico-Musicista' => ['es_ES' => 'Músico/a', 'en_US' => 'Musician'],
    'Negritudes' => ['es_ES' => 'Negritudes', 'en_US' => 'Black identities'],
    'Novas Mídias' => ['es_ES' => 'Nuevos Medios', 'en_US' => 'New Media'],
    'Operador(a) de Som' => ['es_ES' => 'Operador/a de sonido', 'en_US' => 'Sound operator'],
    'Outra função técnica' => ['es_ES' => 'Otra función técnica', 'en_US' => 'Other technical role'],
    'Podcast' => ['es_ES' => 'Podcast', 'en_US' => 'Podcast'],
    'Política' => ['es_ES' => 'Política', 'en_US' => 'Politics'],
    'Povos Indígena' => ['es_ES' => 'Pueblos Indígenas', 'en_US' => 'Indigenous peoples'],
    'Radialista' => ['es_ES' => 'Radialista', 'en_US' => 'Radio broadcaster'],
    'Saúde e Bem Estar' => ['es_ES' => 'Salud y Bienestar', 'en_US' => 'Health and Wellness'],
    'Secretario(a) de Frente' => ['es_ES' => 'Secretario/a de producción', 'en_US' => 'Production secretary'],
    'Turismo' => ['es_ES' => 'Turismo', 'en_US' => 'Tourism'],
    'Técnico de Luz' => ['es_ES' => 'Técnico/a de Luces', 'en_US' => 'Lighting technician'],
    'Técnico(a) de Luz' => ['es_ES' => 'Técnico/a de Luces', 'en_US' => 'Lighting technician'],
    'Técnico(a) de Palco' => ['es_ES' => 'Técnico/a de escenario', 'en_US' => 'Stage technician'],
    'Veganismo' => ['es_ES' => 'Veganismo', 'en_US' => 'Veganism'],
    'Vitrinista' => ['es_ES' => 'Escaparatista', 'en_US' => 'Window dresser'],
];
$__mtr_lcode = \MapasCulturais\i::get_locale();
$__mtr = function (string $pt) use ($__missing_i18n, $__mtr_lcode) {
    return $__missing_i18n[$pt][$__mtr_lcode] ?? $pt;
};
use MapasCulturais\i;

return array(
    1 => array(
        'slug' => 'tag',
        'description' => i::__('Tag'),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Event',
            'MapasCulturais\Entities\Project',
            'MapasCulturais\Entities\Opportunity',
        )
    ),

    2 => array(
        'slug' => 'area',
        'description' => i::__('Área de Atuação'),
        'required' => i::__("Você deve informar ao menos uma área de atuação"),
        'entities' => array(
            'MapasCulturais\Entities\Space',
            'MapasCulturais\Entities\Agent',
            'MapasCulturais\Entities\Opportunity',
        ),
        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Antropologia'),
            $__mtr('Arquitetura-Urbanismo'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Artes Visuais'),
            i::__('Artesanato'),
            $__mtr('Audiovisual e Cinema'),
            i::__('Comunicação'),
            $__mtr('Clima'),
            $__mtr('Cultura Digital e Tecnologia'),
            $__mtr('Geopolitica'),
            $__mtr('Povos Indígena'),
            i::__('LGBTQIAP+'),
            $__mtr('Negritudes'),
            $__mtr('Culturas'),
            i::__('Dança'),
            i::__('Design'),
            i::__('Direito Autoral'),
            $__mtr('Economias'),
            $__mtr('Educação e Formação'),
            $__mtr('Esporte'),
            $__mtr('História e Filosofia'),
            $__mtr('Hospedagem Solidária'),
            i::__('Fotografia'),
            $__mtr('Alimentação'),
            i::__('Gestão Cultural'),
            $__mtr('Games'),
            $__mtr('Jornalismo'),
            $__mtr('Leitura e Literatura'),
            $__mtr('Meio Ambiente'),
            i::__('Redes Sociais'),
            $__mtr('Moda'),
            i::__('Museu'),
            i::__('Música'),
            $__mtr('Novas Mídias'),
            i::__('Produção Cultural'),
            i::__('Rádio'),
            $__mtr('Saúde e Bem Estar'),
            i::__('Teatro'),
            i::__('Televisão'),
            $__mtr('Turismo'),
            $__mtr('Agroecologia'),
            $__mtr('Astronomia e Ufologia'),
            $__mtr('Ciencia'),
            $__mtr('Ciências Sociais'),
            $__mtr('Corpos dissidentes'),
            $__mtr('Direitos Humanos'),
            $__mtr('Juventude'),
            $__mtr('Movimento PCD'),
            $__mtr('Mulher e Feminismos'),
            i::__('Outros'),
            $__mtr('Podcast'),
            $__mtr('Política'),
            $__mtr('Veganismo'),
        )
    ),

    3 => array(
        'slug' => 'linguagem',
        'description' => i::__('Linguagem'),
        'required' => i::__("Você deve informar ao menos uma linguagem"),
        'entities' => array(
            'MapasCulturais\Entities\Event'
        ),

        'restricted_terms' => array(
            i::__('Artes Circenses'),
            i::__('Antropologia'),
            $__mtr('Arquitetura-Urbanismo'),
            i::__('Arte de Rua'),
            i::__('Arte Digital'),
            i::__('Artes Visuais'),
            i::__('Artesanato'),
            $__mtr('Audiovisual e Cinema'),
            i::__('Comunicação'),
            $__mtr('Cultura Digital e Tecnologia'),
            $__mtr('Clima'),
            $__mtr('Geopolitica'),
            $__mtr('Povos Indígena'),
            i::__('LGBTQIAP+'),
            $__mtr('Negritudes'),
            $__mtr('Culturas'),
            i::__('Dança'),
            i::__('Design'),
            i::__('Direito Autoral'),
            $__mtr('Economias'),
            $__mtr('Educação e Formação'),
            $__mtr('Esporte'),
            $__mtr('História e Filosofia'),
            i::__('Fotografia'),
            $__mtr('Alimentação'),
            i::__('Gestão Cultural'),
            $__mtr('Games'),
            $__mtr('Jornalismo'),
            $__mtr('Leitura e Literatura'),
            $__mtr('Meio Ambiente'),
            i::__('Redes Sociais'),
            $__mtr('Moda'),
            i::__('Museu'),
            i::__('Música'),
            $__mtr('Novas Mídias'),
            i::__('Produção Cultural'),
            i::__('Rádio'),
            $__mtr('Saúde e Bem Estar'),
            i::__('Teatro'),
            i::__('Televisão'),
            $__mtr('Turismo'),
            $__mtr('Agroecologia'),
            $__mtr('Astronomia e Ufologia'),
            $__mtr('Ciencia'),
            $__mtr('Ciências Sociais'),
            $__mtr('Corpos dissidentes'),
            $__mtr('Direitos Humanos'),
            $__mtr('Juventude'),
            $__mtr('Movimento PCD'),
            $__mtr('Mulher e Feminismos'),
            i::__('Outros'),
            $__mtr('Podcast'),
            $__mtr('Política'),
            $__mtr('Veganismo'),
        )
    ),
    // 4 => array(
    //     'slug' => 'funcao',
    //     'description' => i::__('Função'),
    //     'entities' => array(
    //         'MapasCulturais\Entities\Agent'
    //     ),
    //     'restricted_terms' => array(
    //         i::__("Aderecista"),
    //         i::__("Adestrador(a) para Artes Cênicas"),
    //         $__mtr("Afinador de Instrumentos"),
    //         i::__("Ajudante de Câmera"),
    //         i::__("Ajudante de Locação"),
    //         i::__("Ajudante de Objetos"),
    //         i::__("Ajudante de Produção"),
    //         i::__("Amestrador(a)"),
    //         i::__("Aplicador(a) de sign"),
    //         i::__("Armeiro(a)"),
    //         i::__("Assessor(a) de Comunicação"),
    //         i::__("Assistente Administrativo"),
    //         i::__("Assistente de Arte"),
    //         i::__("Assistente de Artista Gráfico"),
    //         i::__("Assistente de Backstage"),
    //         i::__("Assistente de Camarim"),
    //         i::__("Assistente de Câmera"),
    //         i::__("Assistente de Cenotécnica"),
    //         i::__("Assistente de Continuidade"),
    //         i::__("Assistente de Controller"),
    //         i::__("Assistente de Criação Artística"),
    //         i::__("Assistente de Edição"),
    //         i::__("Assistente de Edição de Som"),
    //         i::__("Assistente de Eletricista"),
    //         i::__("Assistente de Figurino"),
    //         i::__("Assistente de Ilha de Edição"),
    //         i::__("Assistente de Maquiagem"),
    //         i::__("Assistente de Maquinaria"),
    //         i::__("Assistente de Montagem"),
    //         i::__("Assistente de Objetos"),
    //         i::__("Assistente de Pós Produção"),
    //         i::__("Assistente de Produção (Base ou Set"),
    //         i::__("Assistente de Produção de Arte"),
    //         i::__("Assistente de Produção de Elenco"),
    //         i::__("Assistente de Produção de Locação"),
    //         $__mtr("Assistente de Produção em geral"),
    //         i::__("Assistente de Produção Musical"),
    //         i::__("Assistente de Roteiro"),
    //         i::__("Assistente de Som"),
    //         i::__("Assistente de Transporte"),
    //         i::__("Assistente Mixador(a)"),
    //         i::__("Audiodescritor(a)"),
    //         i::__("Barreira"),
    //         i::__("Bilheteiro(a)"),
    //         i::__("Bordadeiro(a)"),
    //         i::__("Cabeleireiro"),
    //         i::__("Cabeleireiro(a)"),
    //         i::__("Camareiro(a)"),
    //         i::__("Capataz(a) - Montador(a)"),
    //         i::__("Carpinteiro(a)"),
    //         i::__("Cenógrafo(a)"),
    //         $__mtr("Cenotécnico(a)"),
    //         i::__("Chefe de Maquinária"),
    //         i::__("Cinegrafista"),
    //         i::__("Colorista"),
    //         i::__("Colorista Assistente"),
    //         i::__("Consultor de Imagem"),
    //         i::__("Consultor em Legendagem"),
    //         i::__("Consultor(a) em Audiodescrição"),
    //         i::__("Consultor(a) em Braille"),
    //         i::__("Consultor(a) em Libras"),
    //         i::__("Continuista"),
    //         i::__("Contrarregra"),
    //         i::__("Coolhunter"),
    //         i::__("Coordenador(a) de Palco"),
    //         i::__("Cortineiro(a)"),
    //         i::__("Costureiro(a)"),
    //         i::__("Design de Montagem"),
    //         i::__("Diagramador(a)"),
    //         i::__("Digitalizador(a)"),
    //         i::__("Diretor(a) de Palco"),
    //         i::__("Editor de Partituras"),
    //         i::__("Editor(a)"),
    //         i::__("Editor(a) de Som"),
    //         i::__("Eletricista"),
    //         i::__("Eletricista Chefe"),
    //         $__mtr("Engenheiro(a) de Som"),
    //         $__mtr("Ensaiador(a)"),
    //         i::__("Estampador"),
    //         i::__("Figurinista"),
    //         i::__("Foley"),
    //         i::__("Guia-intérprete de língua de sinais"),
    //         $__mtr("Iluminador"),
    //         i::__("Iluminador(a)"),
    //         i::__("Legendista ou Tradutor(a)"),
    //         i::__("Logger"),
    //         i::__("Luthier"),
    //         $__mtr("Maquiador"),
    //         i::__("Maquiador(a)"),
    //         i::__("Maquinista"),
    //         i::__("Marcador(a) de Cena"),
    //         $__mtr("Mediador(a)"),
    //         $__mtr("Mestre(a) de Pista"),
    //         $__mtr("Montador(a)"),
    //         $__mtr("Montador(a) de Palco"),
    //         i::__("Motorista de Audiovisual"),
    //         $__mtr("Músico-Musicista"),
    //         i::__("Operador(a) de Luz"),
    //         $__mtr("Operador(a) de Som"),
    //         $__mtr("Outra função técnica"),
    //         i::__("Passador (a)"),
    //         i::__("Peruqueiro"),
    //         i::__("Peruqueiro(a)"),
    //         i::__("Pilotista"),
    //         i::__("Produtor de Casting"),
    //         i::__("Produtor(a) de Casting/Booker"),
    //         i::__("Produtor(a) Fonográfico"),
    //         $__mtr("Radialista"),
    //         i::__("Roadie"),
    //         i::__("Sapateiro"),
    //         $__mtr("Secretario(a) de Frente"),
    //         i::__("Secretário(a) Teatral"),
    //         i::__("Serigrafista"),
    //         i::__("Sonoplasta"),
    //         i::__("Tatuador"),
    //         $__mtr("Técnico de Luz"),
    //         i::__("Técnico(a) Contábil"),
    //         i::__("Técnico(a) de Estúdio"),
    //         $__mtr("Técnico(a) de Luz"),
    //         $__mtr("Técnico(a) de Palco"),
    //         i::__("Técnico(a) de Som"),
    //         i::__("Técnico(a) de Som Direto"),
    //         i::__("Tradutor(a) ou Intérprete de Libras"),
    //         i::__("Transcritor ou Revisor em Braille"),
    //         i::__("Visagista"),
    //         i::__("Visual Merchandiser"),
    //         $__mtr("Vitrinista"),
    //     )
    // )
);
